version: 2
updates:
  - package-ecosystem: pip
    directory: /api
    schedule:
      interval: daily
      time: '07:00'
    allow:
      - dependency-type: all
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
      major:
        update-types:
          - major
  - package-ecosystem: pip
    directory: /worker
    schedule:
      interval: daily
      time: '07:00'
    allow:
      - dependency-type: all
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
      major:
        update-types:
          - major
  - package-ecosystem: pip
    directory: /shared
    schedule:
      interval: daily
      time: '07:00'
    allow:
      - dependency-type: all
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
      major:
        update-types:
          - major
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
      time: '07:00'
    allow:
      - dependency-type: all
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
      major:
        update-types:
          - major
  - package-ecosystem: docker
    directory: /api
    schedule:
      interval: daily
      time: '07:00'
    allow:
      - dependency-type: all
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
      major:
        update-types:
          - major
  - package-ecosystem: docker
    directory: /worker
    schedule:
      interval: daily
      time: '07:00'
    allow:
      - dependency-type: all
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
      major:
        update-types:
          - major
  - package-ecosystem: npm
    directory: /api/search-component
    schedule:
      interval: daily
      time: '07:00'
    allow:
      - dependency-type: all
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
      major:
        update-types:
          - major
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: '07:00'
    allow:
      - dependency-type: all
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
      major:
        update-types:
          - major
