version: 2.1
orbs:
  lucos: lucos/deploy@0
jobs:
  test-api:
    docker:
      - image: cimg/python:3.14
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -e shared/ -r api/requirements.txt -r api/requirements-test.txt
      - run:
          name: Run tests
          command: cd api && pytest
  test-worker:
    docker:
      - image: cimg/python:3.14
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -e shared/ -r worker/requirements.txt -r worker/requirements-test.txt
      - run:
          name: Run tests
          command: cd worker && pytest
workflows:
  version: 2
  build-deploy:
    jobs:
      - test-api
      - test-worker
      - lucos/build:
          serial-group: << pipeline.project.slug >>/build/<< pipeline.git.branch >>
      - lucos/deploy-avalon:
          serial-group: deploy-avalon
          requires:
            - test-api
            - test-worker
            - lucos/build
          filters:
            branches:
              only:
                - main
